version: "3.8"
services:

  site:
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./conf/site.env
    volumes:
      - ./:/saythanks
    depends_on:
      - db

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./conf/db.env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./saythanks/sqls/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - saythanks

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - ./conf/pgadmin.env

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
    networks:
      - saythanks

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  saythanks: